apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: demo-dev
data:
  FLASK_ENV: "production"
  DATABASE_PATH: "/data/app.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: demo-staging
data:
  FLASK_ENV: "production"
  DATABASE_PATH: "/data/app.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: demo-prod
data:
  FLASK_ENV: "production"
  DATABASE_PATH: "/data/app.db"
